all:
	make -f hello_world.mk all
	make -f ascii_table.mk all
	make -f ascii_table_extended.mk all
	make -f echo.mk all
	#make -C compare all
	make -C dco_calibrate all

clean:
	make -f hello_world.mk clean
	make -f ascii_table.mk clean
	make -f ascii_table_extended.mk clean
	make -f echo.mk clean
	make -C compare clean
	make -C calc clean
	make -C dco_calibrate clean
