waveFile = 'soo.wav';
[y, fs, nbits]=wavread(waveFile);
startIndex=15000;
frameSize=256;
endIndex=startIndex+frameSize-1;
frame = y(startIndex:endIndex);
zeroPaddedFrameSize=16*frameSize;
output=frame2ceps(frame, zeroPaddedFrameSize, 1);
freqStep=fs/zeroPaddedFrameSize;
freqRange=[40, 1000];
index1=round(freqRange(1)/freqStep);
index2=round(freqRange(2)/freqStep);
temp=output; temp(1:index1)=-inf; temp(index2:end)=-inf;
[maxValue, maxIndex]=max(temp);
line(maxIndex, output(maxIndex), 'marker', 'o', 'color', 'r');
axisLimit=axis;
line(index1*[1 1], axisLimit(3:4), 'color', 'r');
line(index2*[1 1], axisLimit(3:4), 'color', 'r');
fprintf('Pitch frequency = %f Hz\n', freqStep*(maxIndex-1));