CREATE TABLE addrbook (
  sn SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR( 255 ) NOT NULL ,
  email VARCHAR( 255 ) NOT NULL ,
  birthday DATE NOT NULL ,
  pic VARCHAR( 255 ) NOT NULL ,
  tel VARCHAR( 255 ) NOT NULL ,
  mtel VARCHAR( 255 ) NOT NULL ,
  addr VARCHAR( 255 ) NOT NULL ,
  note TEXT NOT NULL ,
  usn SMALLINT UNSIGNED NOT NULL ,
  INDEX ( birthday , usn )
);

CREATE TABLE id_passwd (
  usn SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  uname VARCHAR( 255 ) NOT NULL ,
  uemail VARCHAR( 255 ) NOT NULL ,
  id VARCHAR( 255 ) NOT NULL ,
  passwd VARCHAR( 255 ) NOT NULL ,
  UNIQUE (id )
); 
